# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('sub_menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('sub', models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, to='book.Sub', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单管理',
                'db_table': 'sub_menu',
            },
        ),
        migrations.CreateModel(
            name='SubMenu2',
            fields=[
                ('sub_menu2_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('sub', models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, to='book.Sub', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单管理',
                'db_table': 'sub_menu2',
            },
        ),
    ]
