# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单管理',
                'db_table': 'nav',
            },
        ),
        migrations.CreateModel(
            name='Upway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'upway',
            },
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'verbose_name': '分类菜单', 'verbose_name_plural': '分类菜单管理'},
        ),
        migrations.AlterModelTable(
            name='sub',
            table='sub',
        ),
    ]
