# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
