# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='插图')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('product', models.CharField(max_length=255, verbose_name='简介')),
            ],
            options={
                'verbose_name': '主编推荐',
                'db_table': 'produce',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_data', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('prod', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='book.Produce')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'review',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='u_id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
    ]
