# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180730_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
