# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180730_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='出自何地')),
                ('type', models.CharField(max_length=255, verbose_name='类型')),
                ('full_content', models.CharField(max_length=255, verbose_name='简介')),
                ('pro', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='book.Sub')),
            ],
            options={
                'verbose_name': '详情',
                'db_table': 'detail',
            },
        ),
    ]
