# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='pro',
            field=models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='book.Produce'),
        ),
    ]
