# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20180730_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': '购物车',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oder_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField()),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('receiver', models.CharField(max_length=255, verbose_name='接收人')),
                ('mobile', models.IntegerField()),
                ('user_message', models.CharField(max_length=255, verbose_name='买家信息')),
                ('pay_time', models.DateTimeField(auto_now=True)),
                ('uer', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='book.User')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='oder',
            field=models.ForeignKey(db_column='oder_id', on_delete=django.db.models.deletion.CASCADE, to='book.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pro',
            field=models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='book.Produce'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uer',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
    ]
